# Generated by Django 5.0.4 on 2025-05-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresponse',
            name='text_response',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Réponse textuelle'),
        ),
    ]
